### SampleWebApp (см. Properties/launchSettings.json — профиль http)
### http://localhost:5001 https://localhost:7115
@host = http://localhost:5001

### CQRS: команда с событиями в очереди
GET {{host}}/testEventsCommand

### CQRS: generic-команда с результатом string
GET {{host}}/testGenericCommand

### CQRS: generic-запрос с результатом string
GET {{host}}/testGenericQuery

### Swagger UI (только при ASPNETCORE_ENVIRONMENT=Development)
GET {{host}}/swagger

### OpenAPI JSON (Swagger)
GET {{host}}/swagger/v1/swagger.json
